#! /bin/sh

# Backup selected system-wide data such as /etc.  Intended to be run as root.

# source and target directories of backup
NAME=$(basename $0)
SOURCEDIR="/"
TARGETDIR="/media/attila/seagate-attila/$NAME"

## clean up old backups
#PASSPHRASE=chesslab13 duplicity remove-older-than 2Y \
#    file://$TARGETDIR

# the main backup
PASSPHRASE=chesslab13 duplicity \
    --full-if-older-than 1M \
    --log-file ${TARGETDIR}.log \
    --include /etc \
    --exclude '**' \
    $SOURCEDIR \
    file://$TARGETDIR
