#! /bin/sh

# Create backup of /home/attila for work by excluding private directories

# source and target directories of backup
NAME=$(basename $0)
SOURCEDIR="/home/attila"
TARGETDIR="/media/attila/Backup/$NAME"

# list of installed Debian/Ubuntu packages
dpkg -l > ~attila/backup/dpkg.list

# list of installed optional 3rd party packages
find /opt -maxdepth 2 > ~attila/backup/opt.list

# list of locally installed programs
find /usr/local -maxdepth 2 > ~attila/backup/local.list

# clean up old backups
PASSPHRASE=hillbilly duplicity remove-older-than 2Y \
    file://$TARGETDIR

# the main backup
PASSPHRASE=hillbilly duplicity \
    --full-if-older-than 1M \
    --log-file ~attila/backup/${NAME}.log \
    --log-file ${TARGETDIR}.log \
    --exclude $SOURCEDIR/Downloads \
    --exclude $SOURCEDIR/.cache \
    --exclude $SOURCEDIR/data \
    $SOURCEDIR \
    file://$TARGETDIR
