#!/bin/bash

# Usage: build-deploy-notebook [servername]

# For setting up apache webserver on MacOS X see
# https://discussions.apple.com/docs/DOC-3083

# set server to deploy to
SERVER=${1:-bernie}

cd ~/lab-notebook
# build; note the second config file containing server-specific settings
JEKYLL_ENV=production bundle exec jekyll build -c _config.yml,_config.${SERVER}.yml
#bundle exec jekyll build --incremental -c _config.yml,_config.${SERVER}.yml

# deploy to server
rsync -ar --delete-after --delete-excluded _site/ ${SERVER}:~/Sites/

