#! /usr/bin/env bash

# Wrapper of knit-basic for knitting some input.Rmd in projectdir and
# incorporating it into the lab-notebook.

usage="usage: `basename $0` input.Rmd"

if test $# -ne 1; then
    echo $usage
    exit 1
fi

rmdpath=`realpath $1`
projectdir=$HOME/projects
notebookdir=$HOME/lab-notebook

if grep "$projectdir" <<< $rmdpath >/dev/null; then
    project=$(sed "s:$projectdir/\([^/]\+\)/.*$:\1:" <<< $rmdpath)
    knit-basic -b $1 $notebookdir projects/$project
else
    echo "error: use knit-basic instead of `basename $0`"
    exit 1
fi
