#! /usr/bin/env bash

# Wrapper of knit-basic for knitting some input.Rmd in projectdir
# and then incorporating it into the lab-notebook.

usage="usage: `basename $0` input.Rmd|input.ipynb [featimg]"

if test $# -gt 2; then
    echo $usage
    exit 1
fi

rmdpath=`realpath $1`

# lab projects
projectdir=$HOME/projects
notebookdir=$HOME/lab-notebook

# R you experienced?
ruexperienced=$HOME/websites/R-you-experienced

# check which project the Rmd file belongs to and act accordingly
if grep "$projectdir" <<< $rmdpath >/dev/null; then
    project=$(sed "s:$projectdir/\([^/]\+\)/.*$:\1:" <<< $rmdpath)
    case $project in
        monoallelic-brain)
            echo "redirecting $project to open notebook"
            notebookdir=$HOME/websites/open-notebook/$project
            ;;
    esac
    if test -z $2; then
        knit-basic -b $1 $notebookdir projects/$project
    else
        knit-basic -i $2 -b $1 $notebookdir projects/$project
    fi
elif grep "$ruexperienced" <<< $rmdpath >/dev/null; then
    knit-basic $1 $ruexperienced -
else
    echo "error: use knit-basic instead of `basename $0`"
    exit 1
fi
