#!/usr/bin/env bash

type=Somatic # or Germline
numproc=`nproc`
refseq=$REFSEQ
outputDir=$PWD
outputType=z
dbsnp=$DBSNP_ALL 

while getopts 't:p:r:1:2:a:b:o:O:d:x' myopt; do
    case $myopt in
        t) type=$OPTARG;;
        p) numproc=$OPTARG;;
        r) refseq=$OPTARG;;
        1) caseBAM=$(realpath $OPTARG);;
        2) controlBAM=$(realpath $OPTARG);;
        a) caseSample=$OPTARG;;
        b) controlSample=$OPTARG;;
        o) outputDir=$OPTARG;;
        O) outputType=$OPTARG;;
        d) dbsnp=`realpath $OPTARG`;;
        x) exomeOpt='--exome';;
    esac
done

SNfromBAMheader () {
    BAM=$1
    SN=$(samtools view -H $BAM |
    sed -n '/^@RG/ { s/^.*SM:\(\S*\)\s.*$/\1/; p }' |
    sort -u)
    numSamplesinBAM=$(echo $SN | wc -w)
    if test $numSamplesinBAM -ne 1; then
        echo "$BAM contains $numSamplesinBAM samples instead of 1.  Exiting" 1>&2
        exit 1
    fi
    echo $SN
}

caseSample=${caseSample:-$(SNfromBAMheader $caseBAM)}
controlSample=${controlSample:-$(SNfromBAMheader $controlBAM)}


# CALLER FUNCTIONS

lofreqSomatic () {
    outprefix='out-'
    # run lofreq
    cmd="somatic -n $controlBAM -t $caseBAM -f $refseq --threads $numproc -o $outprefix -d $dbsnp"
    eval "/opt/lofreq_star/current/lofreq $cmd"
    # output file names
    vcf=${outprefix}somatic_final.snvs.vcf.gz
    vcfbn=`basename $vcf .vcf.gz`
    outvcf=$vcfbn-samples.vcf.gz
    # add samples and write to outvcf
    addsample=/opt/lofreq_star/current/lofreq2_add_sample.py
    $addsample -i $vcf -o $outvcf -b $controlBAM $caseBAM
    # my way
    caseDefaultSample=`basename $caseBAM`
    controlDefaultSample=`basename $controlBAM`
    $HOME/bin/rename-case-control-samples -a $caseSample -A $caseDefaultSample -b $controlSample -B $controlDefaultSample $outvcf
}

somaticSniper () {
    outprefix='out'
    vcf="$outprefix.vcf"
    cmd="bam-somaticsniper -F vcf -f $REFSEQ $caseBAM $controlBAM $vcf"
    eval $cmd
    $HOME/bin/rename-case-control-samples -a $caseSample -b $controlSample $vcf
}

strelka2 () {
    # some variables
    jobOpt="-j $numproc"
    STRELKA_INSTALL_PATH=/usr/local
    configScript="${STRELKA_INSTALL_PATH}/bin/configureStrelka${type}Workflow.py"
    analysisDir="${outputDir:-.}"
    variantsdir=$analysisDir/results/variants/
    # build config command
    configcmd="$configScript \
        --referenceFasta=$refseq \
        $exomeOpt \
        --runDir=$analysisDir"
    case $type in
        Somatic) configcmd="$configcmd --normalBam=$controlBAM --tumorBam=$caseBAM";;
        Germline) configcmd="$configcmd --bam=$controlBAM --bam=$caseBAM";;
    esac
    # run
    eval $configcmd
    $analysisDir/runWorkflow.py -m local $jobOpt
    # rename case and control samples for Somatic caller
    case $type in
        Somatic)
            cd $variantsdir
            for vcf in *.vcf.gz; do
                echo $vcf
                bcftools view -h $vcf | grep '^#CHROM'
                $HOME/bin/rename-case-control-samples -a $caseSample -b $controlSample $vcf
                bcftools index --tbi $vcf
            done
            ;;
    esac
}

strelka2Germline2s () {
    type=Germline
    strelka2
}

strelka2Somatic () {
    type=Somatic
    strelka2
}

TNseq () {
    export SENTIEON_INSTALL_DIR=/opt/sentieon-genomics/current/
    export SENTIEON_LICENSE="/opt/sentieon-genomics/license/Mount_Sinai_School_of_Medicine_eval.lic"
    sentieon_executable=/opt/sentieon-genomics/current/bin/sentieon
    #TODO: get missing VCF files from somewhere
    if false; then
        sentieon_refdir="`dirname $REFSEQ`/../sentieon"
        bqsr_sites=" -k $sentieon_refdir/Mills_and_1000G_gold_standard.indels.b37.vcf \
            -k $sentieon_refdir/1000G_phase1.indels.b37.vcf \
            -k $sentieon_refdir/dbsnp_138.b37.vcf"
        caseTable=`basename $caseBAM .bam`.qcal.table
        controlTable=`basename $controlBAM .bam`.qcal.table
        # BQSR
        $sentieon_executable driver \
            -t $numproc -r $refseq -i $caseBAM \
            --algo QualCal $bqsr_sites $caseTable
        $sentieon_executable driver \
            -t $numproc -r $refseq -i $controlBAM \
            --algo QualCal $bqsr_sites $controlTable
        # call variants with TNhaplotyper (mutect2)
        $sentieon_executable driver \
            -t $numproc -r $refseq -i $caseBAM -i $controlBAM \
            -q $caseTable -q $controlTable \
            --algo TNhaplotyper \
            --tumor_sample $caseSample --normal_sample $controlSample tnseq.vcf
    fi
    # call variants with TNhaplotyper (mutect2)
    $sentieon_executable driver \
        -t $numproc -r $refseq -i $caseBAM -i $controlBAM \
        --algo TNhaplotyper \
        --tumor_sample $caseSample --normal_sample $controlSample tnseq.vcf
}


for caller in TNseq; do
    outputDir="$outputDir/$caller"
    # create output directory unless it already exists and change to it
    if test -d $outputDir
    then :
    else mkdir $outputDir
    fi
    saveDir=$PWD
    cd $outputDir
    # record runtime and redirect STDOUT and STDERR to log file
    ( time -p $caller ) &>$caller.log
    cd $saveDir
done
