#!/bin/bash
BOWTIE2_INDEX=${BOWTIE2_INDEX:-/sc/orga/projects/chessa01c/refgenome/GRCh37/dna/bowtie2/Homo_sapiens.GRCh37.75.dna.primary_assembly}

# Load my preferred bwa module.  It's best to keep it loaded after the script
# exits.
module load ${MODULE_BOWTIE2:-bowtie2/2.2.8}

# process options
while getopts ":S:p:" opt; do
    case $opt in
        S) SAM=$OPTARG;; # SAM output
        p) p="-p $OPTARG";; # number of threads
    esac
done
shift $(($OPTIND - 1))

# invoke bowtie2
bowtie2 $p -x $BOWTIE2_INDEX -1 $1 -2 $2 -S $SAM
