#! /usr/bin/env bash

usage="`basename $0` cfgfile [output_dir]"

# Example for cfgfile:
#input_VCF_file=/big/results/bsm/2018-05-24-refseq-remap/chr22/NA12892_S1.vcf.gz
#input_chain_file=/big/data/refgenome/mapping/GRCh38_to_GRCh37.chain.gz
#ref_genome_file=/big/data/refgenome/GRCh37/ensembl/release-75/Homo_sapiens.GRCh37.75.dna.toplevel.fa

cfgfile=$1
output_dir=`realpath ${2:-$PWD}`

. $cfgfile

out_vcf=$output_dir/`basename $input_chain_file .chain.gz`-`basename $input_VCF_file .gz`
out_log=$out_vcf.log

#echo "CrossMap.py vcf $input_chain_file $input_VCF_file $ref_genome_file $out_vcf 2> $out_log"
CrossMap.py vcf $input_chain_file $input_VCF_file $ref_genome_file $out_vcf 2> $out_log &&
    bcftools view -O z -o $out_vcf.gz $out_vcf &&
    bcftools sort $out_vcf.gz &&
    bcftools index --tbi $out_vcf.gz
