#!/usr/bin/env bash

installdir=/usr/local
config_script=$installdir/bin/configureStrelkaWorkflow.pl
demo_config_file=$installdir/bin/strelka-demo/strelka_demo_config.ini
#demo_config_file=$installdir/etc/strelka_config_bwa_default.ini
analysis_dir=strelka-out

bam1=$1
bam2=$2
ref=${3:-~/data/GRCh37/dna/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa}


cmd="$config_script \
--normal=$bam1 \
--tumor=$bam2 \
--ref=$ref \
--config=$demo_config_file \
--output-dir=$analysis_dir"

$cmd

# Step 2: run demo (on single local core):
cmd="make -C $analysis_dir"
$cmd

