#!/usr/bin/env bash

while getopts 'p:r:1:2:o:' myopt; do
    case $myopt in
        p) numproc=$OPTARG;;
        r) refseq=$OPTARG;;
        1) caseBAM=$OPTARG;;
        2) controlBAM=$OPTARG;;
        o) outputDir=$OPTARG;;
    esac
done

jobOpt=""
if test -v numproc; then
    jobOpt="-j $numproc"
fi

type=Somatic
STRELKA_INSTALL_PATH=/usr/local
configScript="${STRELKA_INSTALL_PATH}/bin/configureStrelka${type}Workflow.py"

analysisDir="${outputDir:-.}/strelka2${type}"

configcmd="$configScript \
--tumorBam=$caseBAM \
--normalBam=$controlBAM \
--referenceFasta=$refseq \
--exome \
--runDir=$analysisDir"

eval $configcmd

$analysisDir/runWorkflow.py -m local $jobOpt
