#!/usr/bin/env bash

usage="usage: `basename $0` -t Somatic|Germline -p numproc -r refseq.fa -1 case.bam -2 control.bam -o outputDir [-x]"

# print usage without any arguments
if test $# -eq 0; then
    echo $usage >&2; exit 1
fi

# options
type=Somatic
exomeOpt=''
while getopts 't:p:r:1:2:o:x' myopt; do
    case $myopt in
        t) type=$OPTARG;;
        p) numproc=$OPTARG;;
        r) refseq=$OPTARG;;
        1) caseBAM=$OPTARG;;
        2) controlBAM=$OPTARG;;
        o) outputDir=$OPTARG;;
        x) exomeOpt='--exome';;
    esac
done
jobOpt=""
if test -v numproc; then
    jobOpt="-j $numproc"
fi

STRELKA_INSTALL_PATH=/usr/local
configScript="${STRELKA_INSTALL_PATH}/bin/configureStrelka${type}Workflow.py"

analysisDir="${outputDir:-.}/strelka2${type}"

configcmd="$configScript \
--tumorBam=$caseBAM \
--normalBam=$controlBAM \
--referenceFasta=$refseq \
$exomeOpt \
--runDir=$analysisDir"

eval $configcmd

$analysisDir/runWorkflow.py -m local $jobOpt
