#! /usr/bin/env bash

# Create a subwiki from the HTML document with 'fileId' in the project with
# 'projectId'

usage="usage: `basename $0` fileId projectId"

fileId=$1
# the default syn12119642 is the "BSM Chess Lab" project
projectId=${2:-syn12119642}
if test $# -eq 0; then
    echo $usage
    exit 1
fi

knitrscript=$HOME/src/notebook2wiki.R 

Rscript $knitrscript $fileId $projectId
