#! /usr/bin/env bash

# Input 'article.Rmd' is a kramdown flavored R markdown document and 'synowner'.
# synowner is "a Synapse object which will own the resulting WikiPage (usually a
# Project, Folder, or File)"---quoted from the help document of
# knit2synapse::knitfile2synapse R function.
# There is no output; instead, the script does two tasks:
# 1. convert article.Rmd to article.syn.Rmd, a synapse flavored R markdown document
# 2. knit article.syn.Rmd to article, a Wiki subpage on Synapse
# article.html

usage="usage: `basename $0` article.Rmd synowner"

inRmd=$1
# the default syn12119642 is the "BSM Chess Lab" project
synowner=${2:-syn12119642}
if test $# -eq 0; then
    echo $usage
    exit 1
fi
bn="`basename $inRmd .Rmd`"
dn="`dirname $inRmd`"
synRmd="$dn/$bn.syn.Rmd"
knitrscript=$HOME/src/notebook2synapse.R 
#knitrscript=$HOME/src/myknit2synapse.R 

# reformat delimiter for inline equations
sed 's/\(\$\$\)\([^$]\+\)\1/\1\\(\2\\)\1/g' $inRmd > $synRmd
#sed 's/\(\$\$\)\([^$]\+\)\1/\1\\(\2\\)\1/g' $inRmd | sed '/---/, /---/ d' > $synRmd

Rscript $knitrscript $synRmd $synowner && rm $synRmd
