#! /usr/bin/env bash

# Add GT (genotype) annotation to VCF produced by strelka2Somatic and other callers

outputType=v
caseSample=TUMOR
controlSample=NORMAL

while getopts "O:a:b:" opt; do
    case $opt in
        O) outputType=$OPTARG;;
        a) caseSample=$OPTARG;;
        b) controlSample=$OPTARG;;
    esac
done
shift $(($OPTIND - 1))
invcf=$1

usage="usage: `basename $0` [-O v|z -a caseSample -b controlSample] invcf > outvcf"
if test $# -eq 0; then
    echo $usage; exit 0
fi

# get index of case and control sample fields/columns
fieldnames=$(bcftools view -h $invcf | grep '^#CHROM')
caseCol=$(sed "s/^\(.*$caseSample\).*$/\1/" <<<$fieldnames | wc -w)
controlCol=$(sed "s/^\(.*$controlSample\).*$/\1/" <<<$fieldnames | wc -w)

# temp files for VCF pieces
leftPart=`tempfile`
GT=`tempfile`
format=`tempfile`
GTformat=`tempfile`
controlSample=`tempfile`
caseSample=`tempfile`
controlGT=`tempfile`
caseGT=`tempfile`
controlGTsample=`tempfile`
caseGTsample=`tempfile`
outvcf=`tempfile`

# smaller pieces of output
bcftools view -H $invcf | cut -f 1-8 >> $leftPart
bcftools view -H $invcf | cut -f 9 >> $format
bcftools view -H $invcf | cut -f $controlCol >> $controlSample
bcftools view -H $invcf | cut -f $caseCol >> $caseSample
sed 's/.*/GT:/' $leftPart >> $GT
sed 's/.*/0\/0:/' $leftPart >> $controlGT
sed 's/.*/0\/1:/' $leftPart >> $caseGT

# larger pieces of output
bcftools view -h $invcf | sed '/^##FORMAT/q' >> $outvcf
echo '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">' >> $outvcf
bcftools view -h $invcf | sed -n '/^##FORMAT/,$ p' | sed -n '2,$ p' >> $outvcf
paste -d '' $GT $format >> $GTformat
paste -d '' $controlGT $controlSample >> $controlGTsample
paste -d '' $caseGT $caseSample >> $caseGTsample

# entire output in desired type; clean-up
paste $leftPart $GTformat $controlGTsample $caseGTsample >> $outvcf
bcftools view -O $outputType $outvcf
rm $leftPart $GT $format $GTformat $controlSample $caseSample $controlGT $caseGT $controlGTsample $caseGTsample $outvcf
