#! /usr/bin/env bash

# View possibly gzipped input.vcf as a spreadsheet using libre office calc

usage="usage: `basename $0` input.vcf"

if test $# -ne 1; then
    echo $usage 2>&1; exit 1
fi

invcf=$1
outvcf=$(mktemp /tmp/$(basename $invcf).XXXXXX)

# possibly gzipped VCFs
if gzip --test $invcf; then
    catcmd=zcat
else
    catcmd=cat
fi

ls -l $outvcf
$catcmd $invcf | sed -n '/^#CHROM/,$ p' > $outvcf
{ soffice --calc $outvcf; rm $outvcf; } 2>/dev/null &
